title: Discovery Widgets Docs
description: Discovery Widgets Package
remote_theme: pmarsceill/just-the-docs
search_enabled: true
repo_code_url: "https://github.ibm.com/watson-discovery/disco-widgets/blob/master/"
yo_dawg: "![](https://imgflip.com/s/meme/Yo-Dawg-Heard-You.jpg)"
aux_links:
  "Discovery Tooling on GitHub":
    - "//github.ibm.com/watson-discovery/disco-widgets"
